version: '3.9'

services:
  tomcat:
    image: 127.0.0.1:5000/lwplabslogin:latest
    #build: .
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 100M
    ports:
      - "8080:8080"
